/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * solicitaStreaming.java
 *
 * Created on 29-jun-2010, 19:39:52
 */

package Interfaz;

import Cliente.Cliente;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;

/**
 *
 * @author Joaquín
 */
public class solicitaStreaming extends javax.swing.JFrame {

    //Variables para pedir la IP
    Cliente cCliente = null;

    /** Creates new form solicitaStreaming */
    public solicitaStreaming() {
        this.cCliente = new Cliente();

        initComponents();
        this.setTitle("Solicita el archivo de streaming al servidor");
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        ButtonGroup grupoBoton = new ButtonGroup();
        grupoBoton.add(this.radioManual);
        grupoBoton.add(this.radioAuto);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        radioManual = new javax.swing.JRadioButton();
        ipManual = new javax.swing.JTextField();
        radioAuto = new javax.swing.JRadioButton();
        ipAuto = new javax.swing.JTextField();
        aceptarIP = new javax.swing.JButton();
        cancelarIP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radioManual.setText("Establecer dirección IP manualmente");
        radioManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioManualActionPerformed(evt);
            }
        });

        radioAuto.setText("Solicita la dirección IP al servidor maestro");
        radioAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAutoActionPerformed(evt);
            }
        });

        aceptarIP.setText("Aceptar");
        aceptarIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarIPActionPerformed(evt);
            }
        });

        cancelarIP.setText("Cancelar");
        cancelarIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarIPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(radioAuto)
                            .addComponent(radioManual)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(ipManual))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(ipAuto))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(aceptarIP)
                        .addGap(77, 77, 77)
                        .addComponent(cancelarIP)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(radioManual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radioAuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ipAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarIP)
                    .addComponent(cancelarIP))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioManualActionPerformed
        this.ipAuto.setEditable(false);
        this.ipManual.setEditable(true);
    }//GEN-LAST:event_radioManualActionPerformed

    private void radioAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAutoActionPerformed
        this.ipManual.setEditable(false);
        this.ipAuto.setEditable(false);
    }//GEN-LAST:event_radioAutoActionPerformed

    private void cancelarIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarIPActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarIPActionPerformed

    private void aceptarIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarIPActionPerformed

        if(this.radioManual.isSelected()){
            try {
                //Arranco mi servidor de streaming
                //ss.arrancaServer();
                //new Thread(new ServidorStreaming()).start();
                Runtime.getRuntime().exec("java -jar ServidorStream.jar");
            } catch (IOException ex) {
                Logger.getLogger(solicitaStreaming.class.getName()).log(Level.SEVERE, null, ex);
            }
            //Pido la lista de canciones
            cCliente.conexion("dameLISTA", this.ipManual.getText());
        }
    }//GEN-LAST:event_aceptarIPActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new solicitaStreaming().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarIP;
    private javax.swing.JButton cancelarIP;
    private javax.swing.JTextField ipAuto;
    private javax.swing.JTextField ipManual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioAuto;
    private javax.swing.JRadioButton radioManual;
    // End of variables declaration//GEN-END:variables

}
