/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * xBiblioteca.java
 *
 * Created on 13-sep-2010, 18:59:55
 */
package Interfaz;

import Ficheros.ficheros;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Joaquín
 */
public class xBiblioteca extends javax.swing.JDialog {

    private ficheros f = new ficheros();
    private String sFichero = null;

    /** Creates new form xBiblioteca */
    public xBiblioteca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();


        if(System.getProperty("os.name").equalsIgnoreCase("windows 7")){
            sFichero = "Config\\biblioteca.txt";
            this.rellenaLista(sFichero);
            System.out.println("Estas en windows: " + System.getProperty("os.name"));
        }else if (System.getProperty("os.name").equalsIgnoreCase("linux")){
            sFichero = "Config//biblioteca.txt";
            this.rellenaLista(sFichero);
            System.out.println("Estas en linux: " + System.getProperty("os.name"));
        } else {
            this.listaDirectorios.add("Sistema operativo no soportado.");
        }

    }

    public void rellenaLista(String st){
        f.leeFichero(st);
        this.listaDirectorios.add(st);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        agregarBiblioteca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        listaDirectorios = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        agregarBiblioteca.setText("Añadir");
        agregarBiblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarBibliotecaMouseClicked(evt);
            }
        });

        jLabel1.setText("Directorios convertidos en biblioteca de medios:");

        jButton1.setText("Eliminar");

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaDirectorios, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(agregarBiblioteca)
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaDirectorios, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarBiblioteca)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBibliotecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarBibliotecaMouseClicked
        //Creamos el JFileChooser, la ventana de elección de archivos.
        String dir = null;
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int seleccion = fileChooser.showOpenDialog(null);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File directorio = new File("Config");
            if (directorio.exists()) {
                String ruta = directorio.getAbsolutePath();
                System.out.println(ruta);
                dir = (fileChooser.getSelectedFile().toString());
                f.cFichero(ruta, dir, "biblioteca");
            } else {
                if (directorio.mkdir()) {
                    System.out.println("Se ha creado directorio");
                    dir = (fileChooser.getSelectedFile().toString());
                    f.cFichero("Config\\", dir, "biblioteca");
                } else {
                    System.out.println("No se ha podido crear el directorio");
                }
            }

        }
    }//GEN-LAST:event_agregarBibliotecaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                xBiblioteca dialog = new xBiblioteca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBiblioteca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.List listaDirectorios;
    // End of variables declaration//GEN-END:variables
}
